# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Internet of Pi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Internet of Pi
  pod 'Parse'
  pod 'SpinKit'
  pod 'MBProgressHUD'
  pod 'ATHMultiSelectionSegmentedControl'
end
